### ISSUE TITLE
Start project

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/mentoring-project-4#1]
It will be a classical Node.js app:

- Express  as web framework
- pug as template engine
- Mongoose as database library

For the first task create only two pages:

/ -- index page will have a list of topics
/topics/new -- from this page you will be able to create new topics.

A topic should have such fields:
- createdAt 
- title 
- descripction
- tags (list of strings)

Use eslint:recommended.

**Comment by odv** [comment]
@serge-nikitin  Is my tags schema defined correctly? https://github.com/jscraft-org/mentoring-project-4/blob/master/models/Topic.model.js

**Comment by odv** [comment]
I've updated my model/views according to what we've discussed in our mentoring session.
