### ISSUE TITLE
Static files are not included inside pug template files

### ISSUE THREAD

**Issue by odv** [jscraft-org/mentoring-project-4#2]
My public folder stores static CSS and JS files that need to be included inside my pug templates.
https://github.com/jscraft-org/mentoring-project-4/blob/master/src/app.js#L11
Line above specifies that my public files should be served from path: **/static/** path however when I do:
```link(rel='stylesheet', href='/static/css/main.css')```
my page returns 404 not found and I don't understand why since I've specified the path in my app.js  express.static.

**Comment by serge-nikitin** [comment]
path.join(__dirname, 'public')
../public

**Comment by serge-nikitin** [comment]
try this:
path.join(__dirname, '../public')

**Comment by odv** [comment]
That was the issue.
