### ISSUE TITLE
Why can't I store a hash+salt in a variable?

### ISSUE THREAD

**Issue by odv** [jscraft-org/mentoring-project-4#39]
@serge-nikitin This is how my route looks for registration at the moment:
```router.post("/register", (req, res, next) => {
  const { name, email, password } = req.body
  const { confirmPassword } = req.body
  let saltedPassword
  bcrypt.genSalt(8, (err, salt) => {
    if (err) return err
    bcrypt.hash(password, salt, (err, hash) => {
      saltedPassword = `${hash}+${salt}`
    })
  })
  console.log(saltedPassword)

  const userInfo = { name, email, saltedPassword }

  if (name && email && password) {
    if (password !== confirmPassword) {
      const err = new Error("Passwords do not match!")
      err.status = 400
      return next(err)
    }

    User.create(userInfo, (err, user) => {
      if (err) {
        return next(err)
      }
      req.session.userId = user._id
      return res.redirect("/")
    })
  } else {
    const err = new Error("All fields required!")
    err.status = 400
    return next(err)
  }
})```

When I try to register a new user, I get the following error:
User validation failed: saltedPassword: Path `saltedPassword` is required.


What I don't understand is why hash+salt is not saved in **saltedPassword**.

**Comment by serge-nikitin** [comment]
When you have a problem, you should create a new repo with minimum set of libraries to reproduce your problem. Also your new repo should be agnostic about your current project domain data / terminology. So for most of cases it must be a repo with only one file. Which I (and you) can easy run and reproduce a problem. Do you ask me about bcrypt, mongoose or express library?

Just now you have a classic programming problem -- you have unknown bug. It's the most difficult and the most important part -- to find the reason of problem.

So when you create that mini repo, 90% that you will understand the problem yourself.

**Comment by odv** [comment]
I have reproduced this bug in my bcryptjs learning repository since this is related only to it.: https://github.com/odv/learning_bcryptjs/blob/master/src/t1.js

Is this location ok or should I create a special new repo just for this issue?

**Comment by serge-nikitin** [comment]
I don't understand why you concat salt + hash, but it doesn't matter. Your t1.js is wrong. 

You should do this:

Check this code:


const bcrypt = require("bcryptjs")

let saltedPassword

bcrypt.genSalt(10, (err, salt) => {
  if (err) return err
  bcrypt.hash("jscraft1!!.*", salt, (err, hash) => {
    if (err) return err
    saltedPassword = salt + hash
     console.log(saltedPassword) // only here is your saltedPassword is valide
  })
})
/// this is not valid prace. Because you use callbacks

**Comment by serge-nikitin** [comment]
var bcrypt = require('bcryptjs');
bcrypt.genSalt(10, function(err, salt) {
    bcrypt.hash("B4c0/\/", salt, function(err, hash) {
        // Store hash in your password DB.
       hash -- it's already hashed password. Why you contact salt + hash?
    });
});

**Comment by odv** [comment]
@serge-nikitin "salt + hash" was just an automatism that I had from t0 where I wanted to output the salt so that I can see it's random, and the hash.

After reading about async await and promises, I now understand what I did wrong. I've removed that pre hook and added my new code.
